## Post Request

POST https://msp53.brighton.domains/ci527/assignment2/api.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

oid=CD7890XDX&name=Monica&comment=Test2

### Get Request

GET https://msp53.brighton.domains/ci527/assignment2/api.php?oid=CD7890XDX HTTP/1.1